# 河北金融学院 OA 疫情数据自动填报（新版-适配微信小程序版本） GitHub Action 版（Runner：Windows）
# Powered By Luckykeeper <luckykeeper@luckykeeper.site | https://luckykeeper.site> 2022/09/06
# 因 Windows 的 Runner 排队时间容易过长，此 Workflow 停用

name: 每日健康打卡(WindowsRunner)

on: 
  # 定时运行
  # schedule:
  #   - cron:  '11 6 * * *' # 打卡程序运行时间（UTC时间），默认 '11 6 * * *' 即北京时间每天下午2点11分运行，建议设置在非整点避开高峰期避免排队时间过长问题

  # 手动运行
  workflow_dispatch:

jobs:
  dailyFill:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 安装运行环境
        shell: powershell
        run: |
          choco install -y google-chrome-x64
          choco install -y golang

      - name: 下载打卡程序
        shell: powershell
        run: wget -O datafill_new_windows_amd64.exe https://github.com/HBFUer/dataFill_new/releases/download/1.1.0/datafill_new_windows_amd64.exe

      - name: 进行自动打卡
        shell: powershell
        run: .\datafill_new_windows_amd64.exe --oU ${{ secrets.oaUsername }} --oP ${{ secrets.oaPassword }} --adG ${{ secrets.address }} --prove ${{ secrets.prove }} --OAPush rc

      - name: 上传运行截图
        uses: actions/upload-artifact@v3
        with:
          name: 运行截图
          path: ./Screenshots/

